# Generated by Django 3.2.11 on 2022-01-18 22:46

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('closed_on', models.DateField(blank=True, null=True, verbose_name='Closed on')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Chain',
        ),
    ]
