# Generated by Django 3.2.11 on 2022-01-18 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20220118_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storechain',
            name='is_active',
        ),
    ]
